// This file is @generated by prost-build.
/// Defined here to prevent circular imports between logproto & queryrangebase
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CachingOptions {
    #[prost(bool, tag = "1")]
    pub disabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CachedResponse {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    /// List of cached responses; non-overlapping and in order.
    #[prost(message, repeated, tag = "2")]
    pub extents: ::prost::alloc::vec::Vec<Extent>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Extent {
    #[prost(int64, tag = "1")]
    pub start: i64,
    #[prost(int64, tag = "2")]
    pub end: i64,
    #[prost(string, tag = "4")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub response: ::core::option::Option<::prost_types::Any>,
}
